[package]
name = "tpt-halo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tpt-plasma-schemas = { path = "../../crates/tpt-plasma-schemas" }
tpt-physics-math = { path = "../../crates/tpt-physics-math" }
tpt-ui-components = { path = "../../crates/tpt-ui-components" }
tpt-appfront-core = { workspace = true }

[dev-dependencies]
tpt-aether = { path = "../tpt-aether" }
